#!/usr/bin/env node

// @flow

const chalk = require('chalk');
const meow = require('meow');
const path = require('path');
const pkg = require('./../package.json');
const DefaultCommand = require('./../dist/commands/default.js');

const cli = meow({pkg, help: false});
const create = new DefaultCommand({
  input: cli.input,
  flags: cli.flags
});
const catchErr = e => {
  console.error(e);

  process.exit(1);
};
const shouldPrintHelp = create.shouldResolveAndPrintHelp();

if (shouldPrintHelp) {
  create.resolveAndPrintHelp().catch(catchErr);
} else {
  create.exec().catch(catchErr);
}
