#!/usr/bin/env node

// @flow

const cli = require('commander');
const chalk = require('chalk');
const path = require('path');
const pkg = require('./../package.json');
const defaultCommand = require('./../dist/commands/default.js');

cli
  .description('Effortlessly create new files or modules based upon templates in your application.')
  .usage('create [template-id] <...options>')
  .allowUnknownOption()
  .version(pkg.version)
  .parse(process.argv);

defaultCommand().catch(e => {
  console.error(e);

  process.exit(1);
});
